spring:
  profiles:
    active: local # default로 사용될 프로파일 명시
    include: login-client # 분리되어 있는 yml 포함

  datasource:
    url: jdbc:h2:mem:social
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: none

login:
  naver:
    url:
      login: https://nid.naver.com/oauth2.0/authorize
      authentication: https://nid.naver.com/oauth2.0/token
      callback: http://localhost:8080/auth/login/naver/callback
      profile: https://openapi.naver.com/v1/nid/me
  kakao:
    url:
      login: https://kauth.kakao.com/oauth/authorize
      authentication: https://kauth.kakao.com/oauth/token
      callback: http://localhost:8080/auth/login/kakao/callback
      profile: https://kapi.kakao.com/v2/user/me
      disconnect: https://kapi.kakao.com/v1/user/unlink
  google:
    url:
      login: https://accounts.google.com/o/oauth2/v2/auth
      authentication: https://oauth2.googleapis.com/token
      callback: http://localhost:8080/auth/login/google/callback
      scope: https://www.googleapis.com/auth/userinfo.email
      profile: https://www.googleapis.com/oauth2/v1/userinfo
      disconnect: https://oauth2.googleapis.com/revoke

--- # 프로파일을 구분

spring:
  config:
    activate:
      on-profile: local # 해당 프로파일이 선택되었을 때만 활성화

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true

  h2:
    console:
      enabled: true

---

spring:
  config:
    activate:
      on-profile: test

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  sql:
    init:
      mode: never
